FROM python:3.14

WORKDIR /app

RUN pip install uv

COPY pyproject.toml uv.lock ./
RUN uv sync

COPY . .

CMD ["uv", "run", "uvicorn", "services.gateway.main:app", "--host", "0.0.0.0", "--port", "8000"]